Pet/Controllers/HomeController.cs
using Database.Data;
using Microsoft.AspNetCore.Mvc;
using Pet.Models;
using System.Diagnostics;

namespace Pet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var query = _context.pets.ToList();

            return View(query);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pet/Controllers/PetDetailController.cs
using Database.Data;
using Database.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NuGet.Versioning;
using System.Security.Claims;

namespace Pet.Controllers
{
    public class PetDetailController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private ApplicationDbContext _context;

        public PetDetailController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        // GET: PetDetailController
        [Route("/petdetail")]
        public ActionResult Index(string id)
        {
            var pet = _context.pets.FirstOrDefault(x => x.pet_Id == id);
            return View(pet);
        }

        // GET: PetDetailController/Details/5
        public ActionResult AddPetCart(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Check Bill
            var bill = _context.bills.FirstOrDefault(x => x.bill_UserId == userId);
            Bills bills = null;

            if (bill == null)
            {
                bills = new Bills()
                {
                    bill_Id = Guid.NewGuid().ToString(),
                    bill_UserId = userId,
                    bill_StatusPayment = false,
                    bill_Total = 0,
                    bill_StatusReviceOrder = false,
                    bill_StartDateTime = DateTime.Now,
                    bill_checkout = false,
                    bill_Cancel = false
                };

                _context.bills.Add(bills);

                var petInBill = _context.pettInBill.FirstOrDefault(x => x.pib_BillId == bills.bill_Id && x.pib_PetId == id);
                if (petInBill != null)
                {
                    petInBill.pib_Quantity++;
                }
                else
                {
                    PettInBill pettInBill = new PettInBill()
                    {
                        pib_PetId = id,
                        pib_BillId = bills.bill_Id,
                        pib_Quantity = 1,
                    };
                    _context.pettInBill.Add(pettInBill);
                }
                
            }
            else
            {
                
                var petInBill = _context.pettInBill.FirstOrDefault(x => x.pib_BillId == bill.bill_Id && x.pib_PetId == id);
                if (petInBill != null)
                {
                    petInBill.pib_Quantity++;
                }
                else
                {
                    PettInBill pettInBill = new PettInBill()
                    {
                        pib_PetId = id,
                        pib_BillId = bill.bill_Id,
                        pib_Quantity = 1,
                    };
                    _context.pettInBill.Add(pettInBill);
                }
                

            }
            
            

            _context.SaveChanges();

            return Redirect("/cart");
        }

        // GET: PetDetailController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PetDetailController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PetDetailController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PetDetailController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PetDetailController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PetDetailController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Pet/Views/Home/Index.cshtml
@model IEnumerable<Database.Entities.Pets>

@{
    ViewData["Title"] = "Home Page";

}
<link href="~/css/index-style.css" rel="stylesheet" />

<section class="section-content">

    <!-- section bootstrap -->
    <section class="bootstrap-carousel">
        <div id="demo" class="carousel slide" data-ride="carousel">
        </div>

    </section>
    <div>
        <h4>Bestseller</h4>
    </div>
    <section class="list-dog">
        @foreach (var item in Model)
        {
            <div class="info-dog">
                <img src="@item.pet_ImgUrl1" alt="@item.pet_Name" />
                <h6>@item.pet_Name</h6>
                <div>
                    <div class="col40">
                        <a asp-controller="PetDetail" asp-action="Index" asp-route-id="@item.pet_Id">See details</a>
                    </div>
                    <div class="col60">
                        <i class="fas fa-star star1"></i>
                        <i class="fas fa-star star2"></i>
                        <i class="fas fa-star star3 "></i>
                        <i class="fas fa-star star4"> </i>
                        <i class="fas fa-star star5"></i>
                    </div>
                </div>
            </div>
        }
        
        
    </section>
    @*<div>
        <h4>Sale</h4>
    </div>
    <section class="list-dog">
        <div class="info-dog">
            <img src="image/giongcho/akita-inu.jpg" alt="AKITA INU" />
            <h6>AKITA INU</h6>
            <div>
                <div class="col40">
                    <a href="#">See details</a>
                </div>
                <div class="col60">
                    <i class="fas fa-star star1"></i>
                    <i class="fas fa-star star2"></i>
                    <i class="fas fa-star star3 "></i>
                    <i class="fas fa-star star4"> </i>
                    <i class="fas fa-star star5"></i>
                </div>
            </div>
        </div>
        <div class="info-dog">
            <img src="image/giongcho/alaska.jpg" alt="ALASKA" />
            <h6>ALASKA</h6>
            <div>
                <div class="col40">
                    <a href="#">See details</a>
                </div>
                <div class="col60">
                    <i class="fas fa-star star1"></i>
                    <i class="fas fa-star star2"></i>
                    <i class="fas fa-star star3 "></i>
                    <i class="fas fa-star star4"> </i>
                    <i class="fas fa-star star5"></i>
                </div>
            </div>
        </div>
        
    </section>*@
    <div>
        <h4>News</h4>
    </div>
    <article class="news ">
        <div class="one-news ">
            <div>
                <img src="image/giongcho/bulldog.jpg " alt=" " />
            </div>
            <div class="info ">
                <a href="#">
                    American Bully Dogs – Buy and Sell Purebred Bulldogs, Good Price at WelovePets [...]
                </a>
            </div>
        </div>
        <div class="one-news ">
            <div>
                <img src="image/giongcho/tinmuaban.jpg" alt="hinh ảnh" />
            </div>
            <div class="info ">
                <a href="#">
                    How much does a Corgi Pembroke Wales & Cardigan cost? Buy and sell reputable purebred Corgi puppies at WelovePets [...]
                </a>
            </div>
        </div>
        <div class="one-news ">
            <div>
                <img src="image/giongcho/tintuc-hinhanh.jpg " alt="hinh ảnh" />
            </div>
            <div class="info ">
                <a href="#">
                    Instructions for making Vka paper for dogs according to regulations [...]
                </a>
            </div>
        </div>
    </article>

    <div class="back-to-top" id="backtop">
        <a href="">
            <img src="image/icon/icon-backtotop.png" alt="back to top" />
        </a>
    </div>
</section>


<!-- nut go to back -->